### ISSUE TITLE
Different Between PointsForRansac and MatchesForRansac

### ISSUE THREAD

**Issue by gxyu-star** [rpng/R-VIO2#8]
Dear author,
I found there is a different processing between PointsForRansac and MatchesForRansac in your code. Points in PointsForRansac are normalized while points in MatchesForRansac aren't. Is there a reason for this different?

**Comment by huaizheng** [comment]
Hi, thanks for catching this bug. Both should be normalized before being passed to RANSAC. Please feel free to initiate a pull request for that.
